### ISSUE TITLE
How to show loader untill video is loaded

### ISSUE THREAD

**Issue by Suleman218** [davidbritch/dotnet-maui-videoplayer#12]

**Comment by Suleman218** [comment]
@davidbritch Hi , Is there any way of leeitng know in video control of cross-platform to know when an video is prepared to play, i want to show spinner until video is loaded

**Comment by davidbritch** [comment]
@Suleman218 Sure. Take a look at https://github.com/davidbritch/dotnet-maui-videoplayer/blob/main/src/VideoDemos/Views/CustomTransportPage.xaml

**Comment by Suleman218** [comment]
@davidbritch yeah i got it, thanks for referencing
