### ISSUE TITLE
Excpetion running on Windows 11

### ISSUE THREAD

**Issue by belliez** [davidbritch/dotnet-maui-videoplayer#2]
Android works great, but when I run via Windows I get this exception:

`protected override FrameworkElement CreatePlatformView() => throw new PlatformNotSupportedException("No MediaElement control on Windows.");`

**Comment by andrijac** [comment]
Yeah, it would nice to have this running on Windows.

**Comment by andrijac** [comment]
@belliez 
From https://www.davidbritch.com/2022/07/playing-video-with-net-maui_28.html:
"There’s currently no WinUI implementation (due to the lack of a MediaElement control on WinUI) but I’ll add one once WinUI supports playing video."

**Comment by Sergtek** [comment]
[MediaPlayerElement was just added to WinUI 3 (in the Windows App SDK version 1.2 Preview 1)](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel#winui-3). @davidbritch

**Comment by belliez** [comment]
> [MediaPlayerElement was just added to WinUI 3 (in the Windows App SDK version 1.2 Preview 1)](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel#winui-3). @davidbritch

that's great news

**Comment by davidbritch** [comment]
@belliez @nacompllo @andrijac 

Thanks for letting me know folks. I've got it working playing web videos using WinAppSDK 1.2-preview1. I'll check the code in once it's fully working.

**Comment by belliez** [comment]
That's great news, looking forward to it.
